"""Steam Cloud puller backed by scsd (pyscsd/steamCloudSaveDownloader, MIT).

scsd scrapes store.steampowered.com/account/remotestorage rather than using the
Steam API, and self-throttles to stay well under Steam's daily request budget.
That throttling is deliberately left in place.
"""

from __future__ import annotations

from pathlib import Path

from .config import FACTORIO_APPID, SCSD_BIN, SCSD_CONF, STEAM_DIR, Settings
from .log import log
from .proc import run, run_interactive
from .puller import PullError

# steamCloudSaveDownloader/err.py
EXIT_MESSAGES = {
    1: "could not reach Steam; check the container's network access",
    2: "could not parse Steam's save list; the session has probably expired, "
    "re-run the login-steam command",
    3: "could not fetch the Factorio file list from Steam",
    4: "could not parse Steam's file list; Steam changed its page layout, "
    "a newer scsd release is needed",
    10: "Steam login failed",
    11: "no Steam session; run the login-steam command first",
    13: "Steam request budget exhausted for today; the next attempt will wait",
    14: "a previous pull left a lock file behind",
    16: "cannot write to the scsd directory; check PUID/PGID and volume "
    "ownership",
    17: "the Steam session could not be refreshed; re-run the login-steam "
    "command",
}

LOCK_EXIT = 14
SCSD_LOCK = ".scsd.lock"


class ScsdPuller:
    name = "scsd"

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or Settings.from_env()
        self.app_dir = STEAM_DIR / str(FACTORIO_APPID)

    # -- setup ---------------------------------------------------------------

    def write_config(self) -> None:
        STEAM_DIR.mkdir(parents=True, exist_ok=True)
        SCSD_CONF.write_text(
            "\n".join(
                [
                    "# Generated by factorio-mapshot-cloud. Edits are overwritten.",
                    "[General]",
                    f"save_dir = {STEAM_DIR}",
                    f"2fa = {self.settings.steam_2fa}",
                    "",
                    "[Log]",
                    "log_level = 2",
                    "",
                    "[Rotation]",
                    f"rotation = {self.settings.scsd_rotation}",
                    "",
                    "[Target]",
                    "mode = include",
                    f"list = {FACTORIO_APPID}",
                    "",
                ]
            )
        )

    # -- SavePuller ----------------------------------------------------------

    def login(self, username: str) -> int:
        self.write_config()
        log.info("starting Steam login for %s", username)
        log.info(
            "Steam will send a Steam Guard code (%s). Enter it when prompted.",
            self.settings.steam_2fa,
        )
        code = run_interactive([SCSD_BIN, "-f", SCSD_CONF, "-a", username])
        if code == 0:
            log.info("Steam session written to %s", STEAM_DIR)
        else:
            log.error("Steam login failed: %s", describe_exit(code))
        return code

    def pull(self) -> None:
        self.write_config()
        result = run([SCSD_BIN, "-f", SCSD_CONF])
        if result.ok:
            return

        if result.returncode == LOCK_EXIT:
            lock = STEAM_DIR / SCSD_LOCK
            log.warning("clearing stale scsd lock %s and retrying once", lock)
            lock.unlink(missing_ok=True)
            result = run([SCSD_BIN, "-f", SCSD_CONF])
            if result.ok:
                return

        raise PullError(describe_exit(result.returncode))

    def saves(self) -> list[Path]:
        if not self.app_dir.is_dir():
            return []
        # Rotated copies are suffixed .scsd_<n>, so a *.zip glob skips them.
        found = [p for p in self.app_dir.rglob("*.zip") if p.is_file()]
        return sorted(found, key=lambda p: p.stat().st_mtime, reverse=True)


def describe_exit(code: int) -> str:
    known = EXIT_MESSAGES.get(code)
    if known:
        return f"{known} (scsd exit {code})"
    return f"scsd failed with exit {code}"
